"""followers

Revision ID: 253208080260
Revises: 2a5ad63e75bb
Create Date: 2022-01-30 11:24:08.923928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253208080260'
down_revision = '2a5ad63e75bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
